### ISSUE TITLE
please add new node

### ISSUE THREAD

**Issue by ftoledo** [propush/hdpntreqlist#6]
Hi all, i begin use the HotDogEd and i want to add mi node to support points
please add me!

Thanks you!
```
 <node ftnaddress="4:902/26" requestby="email">
        <country>Argentina</country>
        <city>Dock Sud</city>
        <system>Dock Sud BBS</system>
        <sysop>Fernando Toledo</sysop>
        <note>Acceso a Fidonet desde Argentina</note>
        <email>ragnarok@docksud.com.ar</email>
        <protocol>binkp</protocol>
        <ipaddress>bbs.docksud.com.ar</ipaddress>
        <areasfull>https:/bbs.docksud.com.ar/hde_areas</areasfull>
     </node>
```

**Comment by propush** [comment]
Done!

**Comment by ftoledo** [comment]
Thanks. HotDogEd raed it from internet or this file will added to next release? Because I'm still do not see . Maybe cache?

**Comment by propush** [comment]
It has become available immediately after the issue was closed, I've checked - your node is listed. You may have not seen yourself because due to underlying library limitations you cannot have more than 1 point at one node.
If you delete your existing point in hotdoged, I'll be able to see your node and check point request function.

Best regards,
Sergey.

**Comment by ftoledo** [comment]
Okaaaa cool. I just for testing.. thanks again
